"""Inspect the quadratic spatial phase generated by a finite SPEN chirp.

This is an encoding-block Bloch experiment, not a complete SPEN image or xSPEN.
"""

from __future__ import annotations

import argparse
import json
import time
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pypulseq as pp

# Configure the same isolated Julia environment before importing juliacall.
from demo_epi import ROOT  # noqa: F401


def build_chirp(transverse_preparation: bool):
    # Keep BW/T and peak B1 fixed, but use a broad sweep relative to B1 so that
    # the ideal quadratic-phase approximation is accurate in the central FOV.
    fov, duration, bandwidth, peak_rf_hz = 0.22, 16e-3, 16000.0, 1000.0
    system = pp.Opts(
        max_grad=32,
        grad_unit="mT/m",
        max_slew=130,
        slew_unit="T/m/s",
        rf_dead_time=100e-6,
        rf_ringdown_time=20e-6,
        rf_raster_time=0.5e-6,
    )
    seq = pp.Sequence(system)
    if transverse_preparation:
        seq.add_block(
            pp.make_block_pulse(
                np.pi / 2,
                duration=200e-6,
                system=system,
                delay=system.rf_dead_time,
                use="excitation",
            )
        )
    dt = system.rf_raster_time
    t = (np.arange(round(duration / dt)) + 0.5) * dt
    envelope = 1 - np.abs(np.cos(np.pi * t / duration)) ** 40
    sweep_hz = bandwidth * (t / duration - 0.5)
    rf_phase = np.pi * bandwidth / duration * (t - duration / 2) ** 2
    signal = peak_rf_hz * envelope * np.exp(1j * rf_phase)
    gradient = pp.make_trapezoid(
        "y",
        amplitude=bandwidth / fov,
        flat_time=duration,
        rise_time=100e-6,
        system=system,
    )
    rf = pp.make_arbitrary_rf(
        signal,
        flip_angle=np.pi,
        no_signal_scaling=True,
        dwell=dt,
        delay=gradient.rise_time,
        system=system,
        use="refocusing",
    )
    seq.add_block(rf, gradient)
    seq.set_definition(
        "Name", "spen_chirp_phase" if transverse_preparation else "chirp_inversion"
    )
    seq.set_definition("FOV", [fov, fov, 0.005])
    ok, errors = seq.check_timing()
    if not ok:
        raise RuntimeError(f"Chirp timing check failed: {errors}")
    return (
        seq,
        t,
        signal,
        sweep_hz,
        {
            "fov_m": fov,
            "chirp_duration_s": duration,
            "sweep_bandwidth_hz": bandwidth,
            "time_bandwidth_product": duration * bandwidth,
            "rf_peak_hz": peak_rf_hz,
            "rf_peak_uT": peak_rf_hz / system.gamma * 1e6,
            "gradient_hz_m": bandwidth / fov,
            "gradient_mT_m": bandwidth / fov / system.gamma * 1e3,
            "rf_raster_s": dt,
            "wurst_exponent": 40,
            "rf_normalization": "explicit peak B1; no RF-area flip-angle rescaling",
            "quadratic_coefficient_magnitude_rad_m2": 2
            * np.pi
            * duration
            * bandwidth
            / fov**2,
            "timing_check_passed": bool(ok),
        },
    )


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=Path("runs/spen_chirp_260917"))
    args = parser.parse_args()
    output = args.output.resolve()
    output.mkdir(parents=True, exist_ok=True)
    seq, t, rf, sweep, meta = build_chirp(True)
    inv_seq, *_ = build_chirp(False)
    seq.write(str(output / "spen_encoding.seq"))
    inv_seq.write(str(output / "chirp_inversion.seq"))
    y = np.linspace(-0.6 * meta["fov_m"], 0.6 * meta["fov_m"], 1201)
    fit_mask = np.abs(y) < 0.35 * meta["fov_m"]
    print("Loading KomaMRI for chirp Bloch simulation...", flush=True)
    import komamripy as km
    from juliacall import Main as jl

    scanner = km.Scanner(
        limits=km.HardwareLimits(B0=3.0, B1=40e-6, Gmax=32e-3, Smax=130.0)
    )
    make_obj = jl.seval("""y -> KomaMRI.Phantom(name="1d_chirp_spins",
        x=zeros(length(y)), y=collect(y), T1=fill(1e6,length(y)), T2=fill(1e6,length(y)))""")
    obj = make_obj(y)
    encoded, timings = {}, {}
    for name, path, dt_rf in [
        ("encoding_coarse", "spen_encoding.seq", 0.25e-6),
        ("encoding_fine", "spen_encoding.seq", 0.125e-6),
        ("inversion", "chirp_inversion.seq", 0.25e-6),
    ]:
        sequence = km.read_seq(str(output / path))
        params = km.core.default_sim_params()
        params["return_type"] = "state"
        params["gpu"] = False
        params["precision"] = "f64"
        params["Δt_rf"] = dt_rf
        start = time.perf_counter()
        result = km.simulate(obj, sequence, scanner, sim_params=params)
        encoded[name] = {
            "xy": np.asarray(result.xy).copy(),
            "z": np.asarray(result.z).copy(),
        }
        timings[name] = time.perf_counter() - start
        print(f"{name}: {timings[name]:.2f} s", flush=True)
    mxy = encoded["encoding_fine"]["xy"]
    phase = np.unwrap(np.angle(mxy[fit_mask]))
    coeffs = np.polyfit(y[fit_mask], phase, 2)
    fitted = np.polyval(coeffs, y[fit_mask])
    predicted = meta["quadratic_coefficient_magnitude_rad_m2"]
    coefficient_error = abs(abs(coeffs[0]) - predicted) / predicted
    phase_rms = float(np.sqrt(np.mean((phase - fitted) ** 2)))
    convergence = float(
        np.linalg.norm(encoded["encoding_coarse"]["xy"][fit_mask] - mxy[fit_mask])
        / np.linalg.norm(mxy[fit_mask])
    )
    inversion_mean = float(np.mean(encoded["inversion"]["z"][fit_mask]))
    checks = {
        "fit_region": "central 70% of sweep-defined FOV",
        "expected_abs_quadratic_coefficient_rad_m2": predicted,
        "fitted_coefficients_rad_m2_rad_m_rad": coeffs.tolist(),
        "quadratic_coefficient_relative_error": float(coefficient_error),
        "quadratic_fit_residual_rms_rad": phase_rms,
        "rf_step_halving_relative_mxy_change": convergence,
        "inversion_mean_mz": inversion_mean,
        "min_transverse_magnitude_in_fit_region": float(np.min(np.abs(mxy[fit_mask]))),
        "passed": bool(
            coefficient_error < 0.03
            and phase_rms < 0.3
            and convergence < 0.005
            and inversion_mean < -0.98
        ),
    }
    meta.update(
        spin_count=y.size,
        simulation_seconds=timings,
        simulation_rf_steps_s=[0.25e-6, 0.125e-6],
        koma_version=str(jl.seval("pkgversion(KomaMRI)")),
        assumptions=[
            "1D fixed spins; B0 offset zero; B1 scale one",
            "T1=T2=1e6 s to isolate encoding phase",
            "no ADC or reconstruction in this encoding-block experiment",
            "quadratic-phase SPEN building block; not crossed-chirp xSPEN",
            "finite-duration RF; inversion verified independently using initial Mz=1",
        ],
    )
    np.savez_compressed(
        output / "data.npz",
        y_m=y,
        rf_times_s=t,
        rf_hz=rf,
        sweep_hz=sweep,
        fit_mask=fit_mask,
        fit_phase_rad=phase,
        fit_coefficients=coeffs,
        **{
            f"{name}_{component}": values
            for name, parts in encoded.items()
            for component, values in parts.items()
        },
    )
    (output / "metadata.json").write_text(json.dumps(meta, indent=2), encoding="utf-8")
    (output / "validation.json").write_text(
        json.dumps(checks, indent=2), encoding="utf-8"
    )
    fig, axs = plt.subplots(2, 3, figsize=(14, 8), layout="constrained")
    axs[0, 0].plot(t * 1e3, np.abs(rf), color="#2563eb")
    axs[0, 0].set(
        title="WURST RF envelope", xlabel="RF time (ms)", ylabel="B1 amplitude (Hz)"
    )
    axs[0, 1].plot(t * 1e3, sweep / 1e3, color="#2563eb")
    axs[0, 1].set(
        title="Linear frequency sweep", xlabel="RF time (ms)", ylabel="Frequency (kHz)"
    )
    axs[0, 2].plot(y * 1e3, encoded["inversion"]["z"], color="#2563eb")
    axs[0, 2].axhline(-1, ls="--", color="gray", lw=1)
    axs[0, 2].set(
        title="Inversion test: initial Mz = 1",
        xlabel="Position y (mm)",
        ylabel="Final Mz / M0",
    )
    axs[1, 0].plot(y * 1e3, np.abs(mxy), color="#2563eb")
    axs[1, 0].set(
        title="90-deg pulse + chirp: transverse amplitude",
        xlabel="Position y (mm)",
        ylabel="|Mxy| / M0",
    )
    axs[1, 1].plot(
        y[fit_mask] * 1e3, phase, label="Bloch result", color="#2563eb", lw=2
    )
    axs[1, 1].plot(
        y[fit_mask] * 1e3, fitted, "--", label="Quadratic fit", color="#ea580c"
    )
    axs[1, 1].set(
        title="SPEN quadratic encoding phase",
        xlabel="Position y (mm)",
        ylabel="Unwrapped phase (rad)",
    )
    axs[1, 1].legend()
    axs[1, 2].plot(y[fit_mask] * 1e3, phase - fitted, color="#2563eb")
    axs[1, 2].set(
        title=f"Fit residual: RMS {phase_rms:.3f} rad",
        xlabel="Position y (mm)",
        ylabel="Phase residual (rad)",
    )
    for ax in axs.flat:
        ax.grid(alpha=0.2)
    for ax in [axs[0, 2], axs[1, 0]]:
        ax.axvspan(
            -0.35 * meta["fov_m"] * 1e3,
            0.35 * meta["fov_m"] * 1e3,
            alpha=0.08,
            color="green",
        )
    fig.suptitle(
        "SPEN encoding-block Bloch demo | 16 ms chirp | 16 kHz sweep | R = 256\n"
        "Finite RF + encoding gradient; shaded region used for validation; no full SPEN image yet",
        fontsize=13,
    )
    fig.savefig(output / "chirp_encoding.png", dpi=180)
    plt.close(fig)
    print(json.dumps(checks, indent=2), flush=True)
    print(f"Results: {output}", flush=True)
    if not checks["passed"]:
        raise RuntimeError("Chirp validation failed; inspect validation.json")


if __name__ == "__main__":
    main()
