import React, {useEffect, useMemo, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity, Search, Layers, ArrowUpRight, Download, X, SlidersHorizontal, ChevronRight, Info, ScanLine, FolderOpen, Maximize2} from 'lucide-react';
import './style.css';

const panels = {
  sorted_samples:['原始 ADC','排序后的采样信号 · log RSS'], rofft_original:['RO FFT','读出方向傅里叶变换 · RSS'],
  inva_corrected:['Phase Map + InvA','相位校正后 · RSS'], tikhonov_coils:['Tikhonov','相位校正后 · RSS'],
  scanner_preview:['扫描仪原图','2dseq 预览 · 原方向'], inva_uncorrected:['InvA · 未校正','未做相位校正 · RSS'], tikhonov_uncorrected:['Tikhonov · 未校正','未做相位校正 · RSS']
};
const views = {compare4:['四图对比',['sorted_samples','rofft_original','inva_corrected','tikhonov_coils']],recon_pair:['重建对比',['inva_corrected','tikhonov_coils']],uncorrected_pair:['未校正对比',['inva_uncorrected','tikhonov_uncorrected']],...Object.fromEntries(Object.entries(panels).map(([k,v])=>[k,[v[0],[k]]]))};
const statuses = {completed:'双方法完成', partial_reconstruction:'未做相位校正', preview_only:'仅预览', raw_unavailable:'原始信号不可用', completed_with_limitations:'结果有局限', scanner_preview_only:'仅扫描仪预览', failed:'重建未完成', worker_failed:'重建未完成'};
const url = p => '/data/'+p;
const warnings = w => (Array.isArray(w)?w:w?[w]:[]).map(v=>typeof v==='string'?v:v.message||v.reason||JSON.stringify(v));
function Badge({status}) {return <span className={'badge '+(status==='completed'?'good':'limited')}>{statuses[status]||status}</span>}
function Notice({item}) {const values=[...new Set([item.reason,...warnings(item.warnings)].filter(Boolean))];return values.length>0&&<div className="notice"><Info size={14}/><div>{values.map(v=><p key={v}>{v}</p>)}</div></div>}
async function fetchJSON(path, signal) {const r=await fetch(path,{signal});if(!r.ok)throw new Error(`数据读取失败 (${r.status})`);return r.json()}
function ImagePanel({frame,scan,panelKey,onZoom}) {
 const p=frame.panels[panelKey];const [failed,setFailed]=useState(false);
 return <article className="image-card"><div className="image-title"><span>{panels[panelKey][0]}</span><span className="method-dot"/></div>{p&&!failed?<button className="image-stage" onClick={()=>onZoom({p,panelKey,frame,scan})} aria-label={`放大 ${panels[panelKey][0]} ${frame.id}`}><img src={url(p.url)} loading="lazy" alt={`${panels[panelKey][0]} Slice ${frame.s}`} onError={()=>setFailed(true)}/><span className="expand"><Maximize2 size={15}/></span></button>:<div className="image-stage missing"><ScanLine size={27}/><span>{failed?'图像文件不可读取':'暂无此方法图像'}</span><small>{frame.reason||scan.reason||'此帧未保存对应结果'}</small></div>}<div className="image-caption"><span>{panels[panelKey][1]}</span><span>{p?.shape?.join(' × ')}</span></div></article>
}
function App(){
 const [catalog,setCatalog]=useState(null),[error,setError]=useState(''),[exp,setExp]=useState(''),[cases,setCases]=useState([]),[loading,setLoading]=useState(false),[query,setQuery]=useState(''),[view,setView]=useState('compare4'),[zoom,setZoom]=useState(null),[retry,setRetry]=useState(0);
 const dialog=useRef(null); const main=useRef(null);
 useEffect(()=>{const ac=new AbortController();setError('');fetchJSON('/api/catalog',ac.signal).then(d=>{setCatalog(d);const params=new URLSearchParams(location.hash.slice(1));const defaultCase=d.cases.find(c=>c.id===d.default_case_id)||d.cases[0];setExp(d.cases.some(c=>c.experiment===params.get('exp'))?params.get('exp'):defaultCase?.experiment||'');if(views[params.get('view')])setView(params.get('view'));}).catch(e=>{if(e.name!=='AbortError')setError(e.message)});return()=>ac.abort()},[retry]);
 useEffect(()=>{if(!exp)return;const ac=new AbortController();setLoading(true);setCases([]);setError('');fetchJSON('/api/experiments/'+encodeURIComponent(exp),ac.signal).then(d=>{setCases(d.cases);setLoading(false)}).catch(e=>{if(e.name!=='AbortError'){setError(e.message);setLoading(false)}});return()=>ac.abort()},[exp,retry]);
 useEffect(()=>{if(exp)history.replaceState(null,'','#'+new URLSearchParams({exp,view}));},[exp,view]);
 useEffect(()=>{if(zoom)dialog.current?.showModal();},[zoom]);
 const groups=useMemo(()=>{const map=new Map();for(const c of catalog?.cases||[]){if(!map.has(c.experiment))map.set(c.experiment,{name:c.experiment,scans:0,frames:0});const g=map.get(c.experiment);g.scans++;g.frames+=c.frame_count;}return [...map.values()]},[catalog]);
 const filtered=groups.filter(g=>g.name.toLowerCase().includes(query.toLowerCase()));const selected=groups.find(g=>g.name===exp);const keys=views[view][1];const frameCount=cases.reduce((n,c)=>n+c.frames.length,0);
 const changeExp=name=>{setExp(name);window.scrollTo(0,0)};
 return <div className="app"><aside className="sidebar"><a className="brand" href="/"><span className="brand-icon"><Activity size={23}/></span><span>SPEN<span className="brand-sub">RECONSTRUCTION LAB</span></span></a><div className="workspace-label">工作空间</div><div className="nav-active"><Layers size={17}/>重建浏览器<span className="nav-mark"/></div><div className="sidebar-heading"><span>实验数据</span><span>{groups.length}</span></div><label className="search"><Search size={16}/><input aria-label="搜索实验" placeholder="搜索实验名称…" value={query} onChange={e=>setQuery(e.target.value)}/><kbd>⌕</kbd></label><nav className="experiments" aria-label="实验列表">{filtered.map((g,i)=><button key={g.name} className={'experiment '+(exp===g.name?'selected':'')} onClick={()=>changeExp(g.name)} title={g.name}><FolderOpen size={17}/><span><strong>{g.name}</strong><small>{g.scans} 个扫描 <span>·</span> {g.frames} 帧</small></span>{exp===g.name&&<ChevronRight size={14}/>}</button>)}{!filtered.length&&<p className="empty-search">未找到匹配实验</p>}</nav><div className="sidebar-bottom"><span className="online-dot"/><span>本地重建数据<small>只读浏览 · 原始结果</small></span><span className="version">v2.0</span></div></aside>
 <main ref={main}><header className="topbar"><div>工作空间 <ChevronRight size={13}/><span>重建浏览器</span></div><a href="/data/index.html" target="_blank" rel="noreferrer">旧版图集 <ArrowUpRight size={14}/></a></header><div className="content"><div className="page-heading"><div><div className="eyebrow">RECONSTRUCTION EXPLORER</div><h1>每一层，都清晰可见<span>.</span></h1><p>浏览采集数据，比较重建结果。</p></div><span className="read-only"><span className="online-dot"/>已保存的重建结果</span></div>
 <section className="stats" aria-label="数据总览">{[['实验数据组',catalog?.stats.experiments,'组'],['扫描记录',catalog?.stats.cases,'个'],['影像帧',catalog?.stats.frames,'帧'],['双方法完成',catalog?.stats.completed,'帧']].map(([label,value,unit],i)=><div className="stat" key={label}><span>{label}</span><div>{value?.toLocaleString()??'—'}<small>{unit}</small></div><span className="stat-index">0{i+1}</span></div>)}</section>
 <section className="dataset-heading"><div><div className="section-kicker"><span/>当前实验</div><h2>{exp||'加载数据中…'}</h2><p>{selected?.scans??0} 个扫描 <span>·</span> {selected?.frames??0} 帧 <span>·</span> 全部 Slice / Volume / Echo</p></div><a className="button subtle" href="/data/summary.json" download><Download size={15}/>数据清单</a></section>
 <div className="toolbar"><div className="tabs">{['compare4','recon_pair','uncorrected_pair'].map(v=><button key={v} className={view===v?'active':''} onClick={()=>setView(v)}>{views[v][0]}</button>)}</div><div className="toolbar-selects"><label><SlidersHorizontal size={15}/><select aria-label="查看内容" value={view} onChange={e=>setView(e.target.value)}>{Object.entries(views).map(([k,v])=><option key={k} value={k}>{v[0]}</option>)}</select></label><select aria-label="跳至扫描" defaultValue="" onChange={e=>{document.getElementById(e.target.value)?.scrollIntoView({behavior:'smooth',block:'start'});e.target.value=''}}><option value="">跳至扫描</option>{cases.map(c=><option key={c.id} value={c.id}>Scan {c.scan_id} · {c.frames.length} 帧</option>)}</select></div></div>
 <details className="display-info"><summary><Info size={14}/>图像显示与坐标说明</summary><p>全部切片连续展示，Slice / Volume / Echo 索引从 0 开始。点击图像可放大并下载。</p><p>ADC 使用 log(1 + RSS)、p1–p99.5 窗口；其他图使用 RSS、0–p99.5 窗口。各图独立设窗，亮度不能直接用于定量比较。显示按原像素缩放，不做平滑。</p><p>RO FFT 与重建图沿用旧图集翻转方向，不定义解剖方向。扫描仪预览不是配准真值。未校正结果单独列出；下载 NPZ 保留原始数值。</p></details>
 {error?<div className="state-panel" role="alert"><Info/><h3>{error}</h3><button className="button" onClick={()=>setRetry(n=>n+1)}>重新加载</button></div>:loading||!catalog?<div className="state-panel" role="status"><span className="spinner"/>正在加载实验影像…</div>:<section aria-label="全部扫描">{cases.map(c=><section className="scan" id={c.id} key={c.id}><div className="scan-heading"><div className="scan-name"><span className="scan-icon"><ScanLine size={19}/></span><h3>Scan {String(c.scan_id).padStart(2,'0')}</h3><Badge status={c.status}/></div><span className="scan-meta">{c.matrix?.join(' × ')}{c.matrix?' px · ':''}{c.frames.length} 帧</span></div>{c.label&&<p className="scan-label">{c.label}</p>}<Notice item={c}/>{!c.frames.length&&<div className="no-frames">此扫描没有可用影像帧。</div>}{c.frames.map(f=><div className="frame" key={f.id} data-frame-id={f.id}><div className="frame-heading"><div><span className="slice-label">SLICE <b>{String(f.s??0).padStart(2,'0')}</b></span><span>Volume {f.v??0}</span><span>Echo {f.e??0}</span>{f.status!=='completed'&&<Badge status={f.status}/>}</div><a href={url(f.npz)} download><Download size={13}/>NPZ</a></div><Notice item={f}/><div className={'image-grid columns-'+keys.length}>{keys.map(k=><ImagePanel key={f.id+k} frame={f} scan={c} panelKey={k} onZoom={setZoom}/>)}</div></div>)}</section>)}</section>}
 <footer><span>SPEN Reconstruction Lab</span><span>当前展示 {frameCount.toLocaleString()} 帧 · 原生像素预览</span></footer></div></main>
 <dialog ref={dialog} onClose={()=>setZoom(null)} onClick={e=>{if(e.target===dialog.current)dialog.current.close()}}>{zoom&&<><div className="modal-heading"><div><h3>{panels[zoom.panelKey][0]}</h3><p>Scan {zoom.scan.scan_id} · Slice {zoom.frame.s} · Volume {zoom.frame.v} · Echo {zoom.frame.e}</p></div><button autoFocus aria-label="关闭放大图" onClick={()=>dialog.current.close()}><X size={20}/></button></div><div className="zoom-stage"><img src={url(zoom.p.url)} alt={panels[zoom.panelKey][0]}/></div><div className="modal-footer"><span>{zoom.p.shape.join(' × ')} 像素 · 独立设窗</span><a className="button" href={url(zoom.p.url)} download><Download size={15}/>下载 PNG</a></div></>}</dialog></div>
}
createRoot(document.getElementById('root')).render(<App/>);
